### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MasaYan24** [austinnixholm/ThreeFingerDrag#1]
Looks good!

Can you state how to install and run the script as basic information for beginner?

**Comment by austinnixholm** [comment]
Hey, no problem.

To start, head over to the [releases page](https://github.com/austinnixholm/ThreeFingerDrag/releases/) and download & install the latest version. 

After installation is complete, a start menu icon & desktop shortcut should appear on your system. You can start the program from either of these options.

The current version 1.0.3 does not contain an option for "Run after installation" yet but will be available in an upcoming release, so for now the program must be run manually after setup.

Hope this helps!
