### ISSUE TITLE
[SUGGESTION] Portable release

### ISSUE THREAD

**Issue by RndUsr123** [austinnixholm/ThreeFingerDrag#11]
This program is already great; it's functional, lightweight and privacy-friendly yet it's missing a key feature that would make it even better: portable mode.

The uninstaller is over 10 times the size of the executable itself and the only config file required amounts to a grand total of 3 fields... 
I can see why some users might prefer the installer but I think a portable version would be fitting too :)

**Comment by austinnixholm** [comment]
I appreciate the great suggestion! 

This weekend a new version will be released, and I'll package a portable option alongside the installer which will be a standalone .exe download. I'll also include one for the latest version (v1.2.5).

**Comment by RndUsr123** [comment]
Reopening as I noticed the portable release still uses %localappdata%\ThreeFingerDrag to save the config file.
Saving preferences alongside the .exe makes it easier to backup/move the program as well as running it from external media.

**Comment by austinnixholm** [comment]
Good to know! I'll work on implementing that behavior before I bundle the portable release in v1.2.6.
