### ISSUE TITLE
[POSSIBLE BUG] Drag does not always stop after lifting all fingers

### ISSUE THREAD

**Issue by RndUsr123** [austinnixholm/ThreeFingerDrag#12]
While using the Apple Magic Trackpad 2 over Bluetooth, there's a high chance (I'd say 50%) that lifting all fingers doesn't disable dragging. 

Details:
1) wired connection has worked flawlessly for the last few months, something that's still true today
2) dragging resume is set to 100ms in the UI and 1ms in the .ini file. I made sure enough time passed between lifting and dragging again
3) versions before and including v1.1.0 (last without dragging resume) seem to be unaffected, unlike newer ones. 
4) no dragging shape or pattern in particular appears to be the cause
5) dragging might not get disabled even after slowly lifting a finger at a time (~1s each)

Test methodology used:
- drag a window around
- lift all fingers
- slide a single finger or move the mouse
- observe

OS: W10 21H2
Driver used: https://github.com/imbushuo/mac-precision-touchpad
Versions tested:  v1.0.5, v1.1.0, v1.2.0, v1.2.3, 1.2.5

I cannot completely rule out something other than this program is to blame (faulty trackpad, driver issues, BT adapter...).
I can however say that another tool I use (https://github.com/TransposonY/GestureSign) seems to show, thanks to its "Show Gesture Trail" feature, that finger events are correctly recognized

P.S.  If you don't happen to have an Apple MT2 to test, an option to fully switch off dragging resume like it was in v1.1.0 could work too, I think

**Comment by austinnixholm** [comment]
Interesting find! I built the program with my Apple MT2 using the same driver with a wired connection and haven't yet tested it over Bluetooth, so thanks for making me aware of this.

I'll test this out on my system and see if I can replicate the issue.

**Comment by RndUsr123** [comment]
Good to hear about the similar setup, this should make things easier :)

I tested this a little bit more and noticed that while resizing windows with all 3 fingers is ok, lifting 2 and continuing with one may feature a noticeable delay. This also happens when dragging is resumed with a single finger.
It's worth pointing out however that the delay is introduced in v1.1.0 over a wired connection as well, and that its extent depends on the window being resized. As there's no delay with 2/3 fingers or a mouse, this is potentially unrelated.

Just for the sake of it, I'll give a few examples:
- empty explorer folder: no delay
- explorer folder containing 10~20 mixed files and folders (SSD): slight to moderate delay
- explorer folder containing 50 empty .txt files (SSD): very obvious delay 
- explorer folder containing >150 mixed files and folders, totaling >300GB (high-end SSD): very obvious delay 
- explorer folder containing 6 folders totaling >350GB (HDD): no delay
(mostly consistent regardless of view settings. windows are resized continuously in a circular pattern)

I'll open a new issue if this turns out to be its own thing.

**Comment by RndUsr123** [comment]
Not sure if 1.2.6.1 was even supposed to improve this issue, but it got worse: 

- the triple finger drag gesture itself is now hit or miss, meaning it doesn't even register most of the time
- it now happens the vast majority of the time, and with a wired connection too
- dragging is now unstoppable! A mouse click might be required to end it or it'll go on forever; not even clicking the trackpad disables it.

Tried running this with and without GestureSign (another similar gesture utility) in the background but nothing really changed
Not sure how relevant this is but I'm running the program (installer build) as admin in order to allow dragging to work anywhere

**Comment by austinnixholm** [comment]
Hey when you get a chance can you do the following:

1. Open Config folder
2. Set `debug=true` within config.ini
3. Delete log.txt 
4. Start ThreeFingerDrag (v1.2.6.1-SNAPSHOT) 
5. Perform steps to replicate the bug
6. Close the program

I'd recommend keeping the testing as short as possible with just one successful replication to avoid too large of a log file.

After doing this, please send me the log.txt so I can analyze the debug output. I'm curious to know what the differences are in how your system is reporting touchpad data from the MT2.

**Comment by RndUsr123** [comment]
[log.txt](https://github.com/austinnixholm/ThreeFingerDrag/files/14320968/log.txt)

what happened on my system: drag wasn't even recognized for like 20 times as I tried to move a window around, then it worked once but as I lifted all fingers the bug at issue happened. The part where the bug happen should be a sequence of:
1) lifting 3 fingers (at once);
2) sliding movement of a single finger followed by the finger being lifted; (repeat a couple times)
3) a final click to disable dragging, which did work this time around. (not always the case as I've written in the previous comment).
All of this happened wired.

P.S. wrong button :)

**Comment by austinnixholm** [comment]
Thank you for this. I can say that on my end, I also have the issue dragging also gets stuck or will not be recognized very occasionally, and I'll have to reset it with a touchpad click. However, this is not nearly as common as it seems to be for you. 

Not entirely sure what is introducing this weird behavior but I'm going to need to take a day to do some more analysis and hopefully soon I'll have this issue narrowed down.

**Comment by RndUsr123** [comment]
[log.txt](https://github.com/austinnixholm/ThreeFingerDrag/files/14321008/log.txt)

"optimized" log:

this is pretty much just the bug: 
1) 3 finger drag, with a huge initial dalay of maybe 2 seconds (circular pattern)
2) all fingers lifted
3) bug happens, a single finger finger is able to drag (circular pattern)
4) maybe a few more other random actions 

P.S. this is with Bluetooth

**Comment by RndUsr123** [comment]
[log.txt](https://github.com/austinnixholm/ThreeFingerDrag/files/14321062/log.txt)

This hopefully shows the issue that causes drag to never end even after clicking on the trackpad multiple times; you really need to get creative to disable it without a mouse.

Extra notes: 
Windows scaling is set to 200% on a 4k monitor;
All precision touchpad settings are enabled and the cursor speed slider is set to max. 
3 and 4 finger system gestures are off

**Comment by RndUsr123** [comment]
I might have figured out something: the first vertical third of the trackpad surface from the right is problematic.
It's maybe not the only issue but there's strong evidence it's at the very least a big part of it:

- dragging pretty much never works if all 3 fingers are within that area 
- dragging starts working again as soon as fingers from a gesture started within that area leave it
- dragging might end if some fingers enter the area, which potentially causes the bug
- when the never-ending dragging is triggered, 2 fingers within the area can't drag whereas they could if outside of it

Note that it might not be exactly one third; it should be close enough though.
Other programs are not affected by this.

P.S. v1.2.3 and 1.2.5 are also unaffected

**Comment by austinnixholm** [comment]
Thanks for the information, [try out 1.2.6.2-SNAPSHOT](https://github.com/austinnixholm/ThreeFingerDrag/releases/tag/v1.2.6.2-SNAPSHOT) and let me know how if there is any difference in performance, or if the issue has been resolved on your end. 

I've also added a bit more diagnostic information to debug logs which should be helpful if we need to take another look at that.

> I might have figured out something: the first vertical third of the trackpad surface from the right is problematic. It's maybe not the only issue but there's strong evidence it's at the very least a big part of it:
> 
> * dragging pretty much never works if all 3 fingers are within that area
> * dragging starts working again as soon as fingers from a gesture started within that area leave it
> * dragging might end if some fingers enter the area, which potentially causes the bug
> * when the never-ending dragging is triggered, 2 fingers within the area can't drag whereas they could if outside of it
> 
> Note that it might not be exactly one third; it should be close enough though. Other programs are not affected by this.
> 
> P.S. v1.2.3 and 1.2.5 are also unaffected

This is also happening on my MT2 definitely seems to be directly related to the issue. Looking into it now.

**Comment by austinnixholm** [comment]
Alright so I've applied that hotfix (small oversight), and replaced the downloadable files within the 1.2.6.2-SNAPSHOT pre-release to contain the change! 

Go ahead and give that version a try when you can.

**Comment by RndUsr123** [comment]
This definitely fixed it! There's still issues with explorer (the one I detailed in comment #3) but that's unlikely to be related.

**Comment by austinnixholm** [comment]
Yay, glad to hear it! 
If you wouldn't mind, could you open up another issue for the file explorer related problem? 

I'll do my best to replicate it and see what's up.
