### ISSUE TITLE
my workpalce laptop works well, but my home laptop does not. 

### ISSUE THREAD

**Issue by nzin4x** [austinnixholm/ThreeFingerDrag#6]
how can I report current status.
is there any debug mode to diagnosis?

https://github.com/ClementGre/ThreeFingersDragOnWindows works well at my home laptop.
but this s/w is not little bit smooth.

office laptop : intel cpu
home laptop : ryzen 6800u

**Comment by austinnixholm** [comment]
Thanks for your feedback! 

I've made some updates to the software to handle different ways touchpads report data. The new version (v1.2.4) should work better on your home laptop. 

Give it a shot and let me know if it solves your problem. 
You can download the latest version here: [ThreeFingerDrag v1.2.4](https://github.com/austinnixholm/ThreeFingerDrag/releases/tag/v1.2.4).

**Comment by nzin4x** [comment]
dear Austinnixholm/Threefingerdrag

Thanks for your support.

Unfortunately, 1.2.4 also doesn't work at my laptop. now I'm using touchpad
on asus 13s oled.
and I've installed https://github.com/ClementGre/ThreeFingersDragOnWindows
before met you
and removed it to use your s/w

in contrast, i use apple magic trackpad 2 after installing
https://github.com/imbushuo/mac-precision-touchpad/releases,
and 1.2.3 works well.

Can I get a diagnosis report to forward information to you?

best regards.

**Comment by nzin4x** [comment]
I've run diagnostics branch with visual studio.
with debug option I've got some logs. and I've tried to move visual studio window with three finger 2 times.
I've turned off three finger option on touchpad setting
![image](https://github.com/austinnixholm/ThreeFingerDrag/assets/300782/de9582d8-080a-480f-bcab-845b62aae502)


[log.zip](https://github.com/austinnixholm/ThreeFingerDrag/files/13760369/log.zip)

**Comment by austinnixholm** [comment]
Hey, thanks for your patience and for the information from the diagnostic! 

Looks like the information is reporting contact ids 0, 1, and 2. With my changes made in 1.2.4, I believe that the contacts are sorting out contact id 0, which is containing valid information that is being ignored, resulting in the events not being fired!

I think the culprit is this code in `touch_processor.cpp`

```        
ids.erase(std::remove_if(ids.begin(), ids.end(), [](const int id)
        {
            return id > CONTACT_ID_MAXIMUM || id <= 0;
        }), ids.end());
```

To test this, update and checkout to `main` branch, and replace that code with the following. 

```
ids.erase(std::remove_if(ids.begin(), ids.end(), [](const int id)
        {
            return id > CONTACT_ID_MAXIMUM;
        }), ids.end());
 ```
 
 If you can, please try that out and let me know if it helps!

**Comment by nzin4x** [comment]
![image](https://github.com/austinnixholm/ThreeFingerDrag/assets/300782/b0633554-dc38-469a-90c5-ec1af37183a9)

I've tried to checkout main branch and pull it again and pasted your code.
but sadly not working

**Comment by austinnixholm** [comment]
Appreciate the update, sorry that wasn't the fix. 

After revisiting the data from the log file you provided, I realize I may have initially misunderstood the issue.

Our current system expects to receive the identifiers of all three contacts whenever there's a change in movement involving any finger. However, your device appears to only send the identifiers of the fingers that have moved. This discrepancy could be causing the problem we're encountering.

I'll work on a solution for this, and will get back to you as soon as I can.

**Comment by nzin4x** [comment]
sorry. I'm not familiar with c++. if you need any help to get diagnostics report. please let me know.

**Comment by austinnixholm** [comment]
Hey sorry for the long delay in response. 

When you get a chance, please give the provided snapshot version a try and let me know if the behavior has improved on your home laptop. Optionally, you can pull down changes from the feature/new-behavior-support and run the program manually instead.

[ThreeFingerDrag.1.2.6.1-SNAPSHOT.zip](https://easyupload.io/e3q25w)

**Comment by nzin4x** [comment]
I tried to download but failed. but windows defender it includes virus. "Wacapew.C!ml"
so I've turned off realtime detector of windows defender
so I could download that file. after that I've turned on realtime detector again.
and the file was removed automatically by windows defender.
I couldn't run this program. could you please check file?

**Comment by austinnixholm** [comment]
Oops! Looks like I'm getting the same false positive from Windows Defender when trying to download the file directly via GitHub, can you try downloading it via the easyupload link here? 

https://easyupload.io/e3q25w

**Comment by nzin4x** [comment]
same result.

**Comment by austinnixholm** [comment]
Try out this installer that I've compiled for you and it should behave like a normal release would:

https://easyupload.io/p4tfab

**Comment by nzin4x** [comment]
download was blocked again.
I can turned off windows defender for feature test purpose. but anyway this
file also might not be installed to another github users.

**Comment by austinnixholm** [comment]
Sorry for the inconvenience here. Keep Windows Defender settings normal and I'll get this posted on the repository as a pre-release and I'll get back to you.

**Comment by austinnixholm** [comment]
I've just published the pre-release for the snapshot, feel free to head over there and try again. 

https://github.com/austinnixholm/ThreeFingerDrag/releases/tag/v1.2.6.1-SNAPSHOT

**Comment by nzin4x** [comment]
1. this snapshot installer couldn't be download

2. pulled source is also not working

I've checkout out v1.2.6.1-SNAPSHOT tag and run app within visual studio.
but 3 firger dragging is not working

3. here is my diagnostics log.

best regards.

**Comment by austinnixholm** [comment]
Hi, thank you for trying that out. I'm not sure why the installer couldn't download, however I also bundled a standalone executable within the pre-release you can try too. I'll try to figure out why there are download issues.

Regarding pulling source code:

The changes that I've made are not on the main branch, so unfortunately the changes you pulled were not from the snapshot.

Please fetch all remotes so you can see the new branch, and checkout to `feature/new-behavior-support` and try running the code from Visual Studio again. 
![image_2024-02-17_191819283](https://github.com/austinnixholm/ThreeFingerDrag/assets/7199767/ae39a6c8-67c1-48cd-ba24-3e2f5aef6a40)

**Comment by nzin4x** [comment]
I've switched branch origin/feature/new-behavior-support and not yet
working on my laptop.
i'm pasting log again.

my windows defender detect virus is in installer. and it blocks to download.

**Comment by austinnixholm** [comment]
I'm not seeing the log.txt here, can you try to re-attach it to your post again?

**Comment by nzin4x** [comment]
OK. But 6 hours later. Thanks.

2024년 2월 18일 (일) 12:28, Austin Nixholm ***@***.***>님이 작성:

**Comment by nzin4x** [comment]
this is the log of new-behavior-support branch.

**Comment by austinnixholm** [comment]
Sorry but I'm still not seeing it here, that's strange. I'm thinking that the file size of log.txt might be too large for GitHub.

Can you try the following steps?

1. Open Config folder
2. Delete `log.txt` 
4. Start ThreeFingerDrag
5. Try to perform the gesture once (three fingers down, then move and lift up all fingers)
6. Close the program
7. Upload the newly generated `log.txt`

This should result in a smaller diagnostic file to send.

**Comment by nzin4x** [comment]
But.. to reduce size. I'm clear log file every time..

https://drive.google.com/file/d/1vhfIG2CFzCneWbGAsmVSWlcRjfydUVLA/view?usp=drivesdk

Here is file link

2024년 2월 19일 (월) 04:21, Austin Nixholm ***@***.***>님이 작성:

**Comment by nzin4x** [comment]
I've reset my laptop. and now this works well. 
I'm really happy to use this!
