### ISSUE TITLE
[BUG] v1.2.4 broke double tapping on the Apple Magic Trackpad 2

### ISSUE THREAD

**Issue by RndUsr123** [austinnixholm/ThreeFingerDrag#9]
As the title suggests, version 1.2.4 introduces a bug with the Apple MT2: double tapping effectively is now impossible.  The issue is there's a far too large delay between recognized taps (not clicks) to trigger OS functions like file opening, so file renaming is triggered instead.

v1.2.5 is also affected.

Driver used: https://github.com/imbushuo/mac-precision-touchpad
OS version: W10 21H2

**Comment by austinnixholm** [comment]
Thanks for reporting this issue! 
Just to confirm, are you referring to double-tapping with three fingers?

**Comment by RndUsr123** [comment]
Oops, I indeed forgot to mention that I meant double tapping with a single finger. A few more details:

1) "Tap with a single finger to single-click" and "Tap twice and drag to multi-select" are both enabled in touchpad settings 
2) this issue affects actions like opening files, triggering the selection rectangle and dragging windows around
3) double tapping the title bar to maximize windows works fine
4) double clicking (as opposed to just tapping) to open files and folders in Explorer also works fine
5) none of the mentioned actions is affected in v1.2.3

I hope this helps :)

**Comment by austinnixholm** [comment]
After recreating the bug, it seems that the default single finger double-tap behavior was indeed broken with the changes made since v1.2.4. I appreciate the detailed report!

Looking into a solution and this should be resolved in the upcoming release.

**Comment by RndUsr123** [comment]
Update: double tapping works fine most of the time over Bluetooth

**Comment by austinnixholm** [comment]
I've made some changes and have resolved the double-tapping issue & improved support for Bluetooth mode. So far the snapshot below has been stable on my Magic Trackpad 2.  

When you get a chance, please give the provided snapshot version a try and let me know if the behavior has improved on your system.

[ThreeFingerDrag.1.2.6.1-SNAPSHOT.zip](https://github.com/austinnixholm/ThreeFingerDrag/files/14320204/ThreeFingerDrag.1.2.6.1-SNAPSHOT.zip)

**Comment by RndUsr123** [comment]
Is there a chance the snapshots could be directly uploaded here in the comments? That hosting service seems to refuse requests unless adblocking and/or third-pary scripts blocking are disabled, something I'm definitely not doing.
Really sorry about the inconvenience.

**Comment by austinnixholm** [comment]
No worries at all! I've been having some trouble figuring out how to send a the snapshot executable within these issues posts without it getting flagged and I guess EasyUpload wasn't the best choice, so I apologize for that. 

GitHub won't let me upload the executable directly so let's try this alternative mirror.
Let me know if we need to try something else!

https://file.io/goFuKaGDRRgn

**Comment by austinnixholm** [comment]
I've just published the pre-release for the snapshot, feel free to head over there and try again.

https://github.com/austinnixholm/ThreeFingerDrag/releases/tag/v1.2.6.1-SNAPSHOT

I'll remove the previous links above to avoid any confusion, thanks for baring with me on this.

**Comment by RndUsr123** [comment]
Tested this new build for a bit and it does indeed fix double tapping for me, both with bluetooth and without.
Not sure if this build is supposed to address that too, but the other issue about never-ending drag got worse. Nonetheles, this one can be closed as completed
